# New ports collection makefile for:   libcapsicum
# Date created:        15 May 2011
# Whom:                jonathan
#

PORTNAME=      libcapsicum
PORTVERSION=   0.1alpha
CATEGORIES=    security
MASTER_SITES=  http://www.cl.cam.ac.uk/research/capsicum/

MAINTAINER=    jonathan@FreeBSD.org
COMMENT=       A library for easy sandboxing, to help developers make effective use of Capsicum

MAN3=          libcapsicum.3 libcapsicum_host.3 libcapsicum_sandbox.3
MANCOMPRESSED= yes
#USE_IMAKE=     yes

.include <bsd.port.mk>
